spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: new_password
  jpa:
    show-sql: true
  jmx:
    enabled: false
  devtools:
    restart:
      enabled: false